# Generated by Django 3.2.12 on 2022-03-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='topic',
        ),
        migrations.AddField(
            model_name='document',
            name='topics',
            field=models.ManyToManyField(related_name='document_topics', to='filesystem.Topic'),
        ),
    ]
